//Q1
const prompt = require("prompt-sync")( );
let array = [23,46,37,57,83,60,40,38,21,47]
let a = prompt("Enter a number to be added in the array: ")
a = Number.parseInt(a)
array.push(a)
console.log(array)

//Q2
const prompt = require("prompt-sync")( );
let array = [23,46,37,57,83,60,40,38,21,47]
let a;
 do {
   a = prompt("Enter a number : ")
   a = Number.parseInt(a)
   array.push(a)
 } while (a != 0);
console.log(array)

//Q3

console.log("Question 3 soln below:")
let array1 = [11,26,40,90,37,85,219]
 let num1 = array1.filter((x)=>{
   return x%10 == 0
 })
 console.log(num1)
console.log("\n")


//Q4
console.log("Question 4 soln below:")
 let array2 = [2,5,3,8,12]
 let num2 = array2.map((y)=>{
   return y*y
})
 console.log(num2)
console.log("\n")

//Q5
console.log("Question 5 soln below:")
let array3 = [1, 2, 3, 4, 5, 6, 7]
let num3 = array3.reduce((z1, z2) => {
  return z1 * z2
})
console.log(num3)

//Task_1
let targetNumber = Math.floor(Math.random() * 100 + 1);
let attempts = 0;
let userGuess;

console.log(
  "This is a guessing game, and you have to enter a number. If it matches the number generated by the computer, then you win...\n",
);

userGuess = prompt("Enter a number between 1 and 100");
++attempts;

do {
  userGuess = Number.parseInt(userGuess);

  if (userGuess > targetNumber) {
    console.log("The entered number is greater");
    userGuess = prompt("Enter again!!");
    userGuess = Number.parseInt(userGuess);
    ++attempts;
    continue;
  } else if (userGuess < targetNumber) {
    console.log("The entered number is smaller");
    userGuess = prompt("Enter again!!");
    userGuess = Number.parseInt(userGuess);
    ++attempts;
    continue;
  }
} while (userGuess != targetNumber);

let finalScore = 100 - attempts;
console.log(
  "\nCongratulations🥳🥳\nThe generated number was",
  targetNumber + " and you guessed it right😁\nYour final score is",
  finalScore,
);
